micronaut:
  application:
    name: keyManager

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5434/keymanager`}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

itau:
  accounts:
    url: 'http://localhost:9091'

bcb:
  pix:
    url: 'http://localhost:8082'